name: DCO-CHECK
on:
  pull_request:
    branches:
      - master
jobs:
  check:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    container: christophebedard/dco-check
    steps:
    - uses: actions/checkout@v2
    - run: dco-check
