name: DCO-CHECK
on:
  pull_request:
    branches:
      - master
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: "Install Action"
      uses: hectorcustodio/dco-check-action
    - name: Check DCO
      run: dco-check