name: DCO-CHECK
on:
  pull_request:
    branches:
      - master
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: "Install Action"
      uses: github.com/hectorcustodio/dco-check-action@v1
    - name: Check DCO
      run: dco-check
