name: Release

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master

    - name: get current version 
      run: 'echo CURRENT_VERSION=$(node bin/utils)>> $GITHUB_ENV'

    - uses: actions/checkout@v2 

    - name: get new version
      run: 'echo PACKAGE_VERSION=$(node bin/utils)>> $GITHUB_ENV'

    - name: creates release
      if: ${{env.PACKAGE_VERSION > env.CURRENT_VERSION}}
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: "v${{ env.PACKAGE_VERSION }}"
        commit: master
        body: "Initial release"