name: Score Card
on:
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  Results:
    runs-on: ubuntu-latest
   
    steps:

      - name: Generate File name
        run: |
          IN="${{github.repository}}"
          arrIN=(${IN//// })
          echo ${arrIN[1]}

      - name: Generate Scorecard
        run: docker run -e GITHUB_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }} gcr.io/openssf/scorecard:stable --show-details --repo=${{ github.repository }} --format=json > scorecard.json
  
      - name: Upload File
        uses: swimlane/s3-upload-file-action@main
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_S3_BUCKET }}
          file_path: "./scorecard.json"
          file_mime_type: "application/json"
          dest_dir: "scorecard/beagle"
