name: Score Card
on:
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  Results:
    runs-on: ubuntu-latest
   
    steps:
      - run: touch ${{github.repository}}.json
      - run: docker run -e GITHUB_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }} gcr.io/openssf/scorecard:stable --show-details --repo=${{ github.repository }} --format=json > ${{github.repository}}.json
      - run: ls