name: DCO GPG VALIDATOR
on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
  push:

jobs:
  dco-gpg-validator:
    runs-on: ubuntu-latest
    steps:
      - uses: hectorcustodio/dco-validator@beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
